### PR TITLE
Contains Lots of Updates

### PR DESCRIPTION
**Pull request by robertkeizer**

### CODE REVIEW

**Comment by robertkeizer** [comment]
God damn I have to stop going so fast. Sorry.

**Comment by drtobybrown** [comment]
Hi Robert,

First up, great theme and thanks for maintaining it.

I’m a bit of a novice when it comes to web developing and Jekyll and I was wondering if I could ask a question.

Do you know how can I hide the blog functionality on the generated site while maintaining the option to reactivate it later?

In terms of pages, what you have is:
...
-about
-blog
-timeline
...

What I want is:
...
-about
-Some other stuff
-timeline
...

With the option of:
...
-about
-some other stuff
-blog
-timeline
...

I hope that makes sense. Thanks for your time and making an awesome template.

Cheers
Toby



On Nov 17, 2017, at 12:34, Robert Keizer <notifications@github.com<mailto:notifications@github.com>> wrote:

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/le4ker/personal-jekyll-theme/pull/229

Commit Summary

  *   Small update to the readme.
  *   Getting rid of horribly sudo iptables shit.
  *   Stripping out lots of extra stuff.
  *   Minimal site; Hacked up comments in footer.
  *   Merge pull request #1 from odw2017/rk-updates
  *   Adding GA tag..
  *   Merge pull request #2 from odw2017/rk-ga
  *   Changing layout to include join slack system.
  *   Merge pull request #3 from odw2017/rk-ga
  *   Adding build production script so I can remember.
  *   Stupid me.
  *   What the hell. Make it work.
  *   I could vomit.
  *   Massive update.

File Changes

  *   M .gitignore<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-0> (3)
  *   M README.md<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-1> (85)
  *   M _config.yml<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-2> (122)
  *   A _includes/faq.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-3> (7)
  *   M _includes/footer.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-4> (24)
  *   M _includes/header.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-5> (37)
  *   M _includes/js.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-6> (41)
  *   A _includes/map.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-7> (7)
  *   A _includes/partners.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-8> (7)
  *   M _sass/_mixins.scss<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-9> (9)
  *   M about.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-10> (13)
  *   M css/grayscale.scss<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-11> (8)
  *   A faq.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-12> (14)
  *   A img/code3.png<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-13> (0)
  *   A img/nf_logo.png<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-14> (0)
  *   A img/padlock_icon_2.png<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-15> (0)
  *   A img/pegbeer_logo.svg<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-16> (36)
  *   A img/wpg_logo.png<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-17> (0)
  *   M js/typed.min.js<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-18> (2)
  *   A map.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-19> (15)
  *   A partners.html<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-20> (17)
  *   A scripts/build-production<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-21> (3)
  *   M scripts/serve-lan<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-22> (2)
  *   M scripts/serve-lan-production<https://github.com/le4ker/personal-jekyll-theme/pull/229/files#diff-23> (2)

Patch Links:

  *   https://github.com/le4ker/personal-jekyll-theme/pull/229.patch
  *   https://github.com/le4ker/personal-jekyll-theme/pull/229.diff

**Comment by robertkeizer** [comment]
Hey Toby - I think you'll want @le4ker 's input; This PR was a mistake on my part ( a foolish one at that ).

Comments can be used ( `#` ), and I've done that for my own stuff based on this template.

**Comment by le4ker** [comment]
Hi everyone,

Yes I noticed that this PR was opened by mistake, no worries 😄 

:panos

**Pull request closed without merging**
