### PR TITLE
Pygmentation

### LINKED ISSUE #138: Switch code highlight engine to pygments?
Highlight.js might not the best highlighter choice because for codes with a lot of `<` and `>`, it requires manual escaping of the characters with `&lt;` and `&gt;`. For example try this piece of markdown:

```
# Code 1

<pre><code class="c++">
vector< vector<int> > A;
</code></pre>

# Code 2
<pre><code class="c++">
A = vector<> foo();
</code></pre>
```

### PR DESCRIPTION
**Pull request by djcaesar9114**
Issue Fixed #138 
## Proposed Changes
- I changed the hard coded parts (`<pre><code>` etc.) with pymented ones (`{% highlight` etc.)
- I used:
1. `grep -rl '<pre>' . | xargs sed -ir 's/<pre><code\ data-trim\ class="\([a-z]*\)">/\{% highlight\ \1\ %\}/g'`
2.  `grep -rl '</code>' . | xargs sed -ir 's/<\/code><\/pre>/\{% endhighlight %\}/g'`

### CODE REVIEW

**Comment by PanosSakkos** [comment]
@djcaesar9114 good stuff! How about creating a script with your two commands in order for the existing users to migrate to pygments? 😉  

Also, we should remove the highlight.js dependency now that we're switching to pygments.

**Comment by djcaesar9114** [comment]
OK, got it!
I'm on it ;)

**Comment by PanosSakkos** [comment]
@eiselems @joariasl  This is a really good PR, let's test it and merge it to master 😉 

No need for a migration script is needed 😄

**Comment by eiselems** [comment]
@djcaesar9114 is there still work left to be done (besides the merge conflict)?

**Comment by djcaesar9114** [comment]
Good to go ;)

**Comment by eiselems** [comment]
haha shit :/

**Pull request closed without merging**
